
services:
  server:
    build: ./server
    image: server

  coordinator:
    build: ./coordinator
    image: coordinator
    container_name: servercoordinator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'